platform:ios,'8.0'
target 'ZhiXiang' do
pod 'Masonry', '~>1.0.2'
pod 'BGNetwork'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'LGSideMenuController', '~> 2.1.1'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengUShare/Social/ReducedQQ'
pod 'UMengUShare/Social/ReducedSina'
pod 'SDWebImage', '~> 3.8.2'
end
